# Set up environment by configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.environment.name }}
data:
  {{- range .Values.environment.settings }}
  {{ .key }}: {{ .value }}
  {{- end}}